default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: chess_development
test:
  <<: *default
  database: chess_test

production:
  <<: *default
  database: chess_production
  #username: chess
  #password: <%= ENV['CHESS_DATABASE_PASSWORD'] %>